name: Deploy via SFTP

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Create test file
      run: |
        echo "This is a test file created at $(date)" > test_file.txt
        ls -la
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 217.196.61.30
        username: patto200
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22  # Porta SSH padrão
        local_path: ./
        remote_path: /lotominas.site/
        sftp_only: true
        delete_remote_files: false 