name: Deploy via FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Display FTP connection info (without password)
      run: |
        echo "FTP Server: 2a02:4780:14:4dda::1"
        echo "FTP Username: patto200"
        echo "FTP Port: 21"
        echo "Remote Path: /www/wwwroot/lotominas.site/"
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 2a02:4780:14:4dda::1
        username: patto200
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        server-dir: /www/wwwroot/lotominas.site/
        log-level: verbose
        timeout: 120000
        protocol: ftp
        local-dir: ./
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          deploy.php
          deploy_log.txt 